import React from 'react';
import { PieChart, ShieldCheck } from 'lucide-react';

interface ReportCoverPageProps {
    reportDate: string;
    totalCandidates: number;
    customLogo?: string;
}

export const ReportCoverPage: React.FC<ReportCoverPageProps> = ({ reportDate, totalCandidates, customLogo }) => {
    return (
        <div className="print-page w-[210mm] h-[297mm] p-[15mm] flex flex-col relative page-break-after bg-white">
            {/* Decorative Top Accent */}
            <div className="absolute top-0 left-0 w-full h-3 bg-slate-900" />

            {/* Header Info */}
            <div className="flex justify-between items-start mt-6 shrink-0">
                <div>
                    {customLogo ? (
                        <div className="mb-4">
                            <img src={customLogo} alt="Client Logo" className="max-h-16 object-contain" />
                        </div>
                    ) : (
                        <>
                            <div className="bg-slate-900 text-white p-2 rounded-xl inline-block mb-3">
                                <PieChart className="w-8 h-8" />
                            </div>
                            <h2 className="text-sm font-bold text-slate-500 tracking-widest uppercase mb-1">BuildingReportPro™</h2>
                        </>
                    )}
                    <p className="text-xs font-semibold text-slate-400">의사결정 패키지 (Decision Package)</p>
                </div>
                <div className="text-right">
                    <p className="text-xs font-bold text-slate-600 mb-1">발행일: {reportDate}</p>
                    <div className="inline-flex items-center gap-1.5 bg-slate-100 text-slate-700 px-3 py-1 rounded-full text-xs font-bold font-mono">
                        <ShieldCheck className="w-4 h-4 text-emerald-600" />
                        DATA VERIFIED
                    </div>
                </div>
            </div>

            {/* Main Title Area */}
            <div className="flex-1 flex flex-col justify-center shrink-0 my-12">
                <h1 className="text-5xl font-black text-slate-900 tracking-tight leading-tight mb-6">
                    상업용 부동산<br />
                    시나리오별<br />
                    <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">
                        통합 비교 분석 보고서
                    </span>
                </h1>

                <div className="w-20 h-2 bg-blue-600 mb-10" />

                <p className="text-lg font-bold text-slate-700 max-w-[80%] leading-relaxed mb-6">
                    본 보고서는 귀사가 검토 중인 <span className="text-blue-600 bg-blue-50 px-2 rounded">총 {totalCandidates}개의 대안 물건</span>에 대하여
                    임대차, 실입주 매매, 투자용 매매 등 다각도의 시나리오 타당성을 분석합니다.
                </p>

                <div className="bg-slate-50 p-6 rounded-2xl border border-slate-200 border-l-4 border-l-blue-600">
                    <h3 className="text-sm font-black text-slate-800 mb-2">AI Summary Insight</h3>
                    <p className="text-sm text-slate-600 leading-relaxed text-justify">
                        각 대상 물건들의 월간 현금흐름(수익/지출)과 3년 누적 효과를 한눈에 볼 수 있도록 도식화하였으며,
                        후반부 시트에서는 물건별 상세 스펙과 재무 지표(KPI) 산출 내역을 투명하게 제공합니다.
                        이를 통해 직관적이고 데이터에 기반한 최고 경영진의 신속한 의사결정을 지원합니다.
                    </p>
                </div>
            </div>

            {/* Footer Area */}
            <div className="mt-auto pt-6 border-t-[3px] border-slate-900 flex justify-between items-end shrink-0">
                <div>
                    <h4 className="text-base font-black text-slate-900 mb-1">Confidential & Proprietary</h4>
                    <p className="text-xs text-slate-500">
                        본 문서의 내용은 내부 검토용으로만 사용되어야 하며, 외부 유출을 금합니다.
                    </p>
                </div>
                <div className="text-right">
                    <p className="text-xs font-bold text-slate-400">Generated by</p>
                    <p className="text-sm font-black text-slate-900 tracking-tight">BuildingReportPro AI</p>
                </div>
            </div>
        </div>
    );
};
