import React from 'react';
import { BuildingReport } from '@/types/building';
import { AlertTriangle, Building, MapPin, Calendar, Ruler, Car, TrendingUp, Landmark } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

interface ReportViewProps {
  data: BuildingReport;
}

const ReportView: React.FC<ReportViewProps> = ({ data }) => {
  return (
    <div className="w-[210mm] min-h-[297mm] bg-white p-[20mm] mx-auto shadow-lg border print:shadow-none print:border-none print:m-0">
      {/* Header */}
      <div className="border-b-4 border-blue-600 pb-4 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold text-gray-800">부동산 건축물 분석 보고서</h1>
          <p className="text-gray-500 mt-1">Building Analysis Report</p>
        </div>
        <div className="text-right text-sm text-gray-400">
          Generated by Building Report Pro
        </div>
      </div>

      {/* Violation Alert */}
      {data.vlrtBldRgstYn === 'Y' && (
        <div className="bg-red-50 border-2 border-red-500 p-4 mb-6 rounded-lg flex items-center gap-3">
          <AlertTriangle className="text-red-500 h-8 w-8" />
          <div>
            <h3 className="text-red-800 font-bold text-lg">위반건축물 주의</h3>
            <p className="text-red-700 text-sm">본 건축물은 대장에 위반건축물로 기재되어 있습니다. 매매 및 임대차 시 확인이 필요합니다.</p>
          </div>
        </div>
      )}

      {/* Basic Info Card */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4 flex items-center gap-2 border-l-4 border-blue-500 pl-2">
          <Building className="h-5 w-5 text-blue-500" />
          기본 건축물 정보
        </h2>
        <div className="grid grid-cols-2 gap-4 bg-gray-50 p-4 rounded-lg">
          <InfoItem label="건물명" value={data.bldNm || '명칭없음'} icon={<Building className="h-4 w-4" />} />
          <InfoItem label="대지위치" value={data.platAddr} icon={<MapPin className="h-4 w-4" />} />
          <InfoItem label="주용도" value={data.mainPurpsCdNm} />
          <InfoItem label="구조" value={data.strctCdNm} />
          <InfoItem label="사용승인일" value={formatDate(data.useAprvDay)} icon={<Calendar className="h-4 w-4" />} />
          <InfoItem label="규모" value={`지상 ${data.grndFlrCnt}층 / 지하 ${data.ugndFlrCnt}층`} />
        </div>
      </section>

      {/* Land & Price History - v2 Added */}
      <div className="grid grid-cols-2 gap-8 mb-8">
        {/* Land Info */}
        <section>
          <h2 className="text-xl font-bold mb-4 flex items-center gap-2 border-l-4 border-blue-500 pl-2">
            <Landmark className="h-5 w-5 text-blue-500" />
            토지 정보 요약
          </h2>
          <div className="bg-gray-50 p-4 rounded-lg space-y-3">
            <div className="flex justify-between border-b pb-2">
              <span className="text-gray-500">지목</span>
              <span className="font-bold">{data.landInfo?.lndMsclCdNm || '-'}</span>
            </div>
            <div className="flex justify-between border-b pb-2">
              <span className="text-gray-500">대지면적</span>
              <span className="font-bold">{data.landInfo?.lndpclAr.toLocaleString() || '-'} m²</span>
            </div>
            <div className="flex justify-between">
              <span className="text-gray-500">현재 공시지가</span>
              <span className="font-bold text-blue-600">{data.landInfo?.pannPrc.toLocaleString() || '-'} 원 / m²</span>
            </div>
          </div>
        </section>

        {/* Price Chart */}
        <section>
          <h2 className="text-xl font-bold mb-4 flex items-center gap-2 border-l-4 border-blue-500 pl-2">
            <TrendingUp className="h-5 w-5 text-blue-500" />
            공시지가 변동 추이
          </h2>
          <div className="h-[120px] w-full mt-2">
            {data.priceHistory ? (
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={data.priceHistory}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} />
                  <XAxis dataKey="year" fontSize={10} tickLine={false} axisLine={false} />
                  <Tooltip 
                    formatter={(value: any) => [Number(value).toLocaleString() + '원', '지가']}
                    contentStyle={{ fontSize: '12px', borderRadius: '8px' }}
                  />
                  <Line type="monotone" dataKey="price" stroke="#3b82f6" strokeWidth={3} dot={{ r: 4 }} activeDot={{ r: 6 }} />
                </LineChart>
              </ResponsiveContainer>
            ) : (
              <div className="flex items-center justify-center h-full bg-gray-50 rounded text-gray-400 text-xs">데이터 없음</div>
            )}
          </div>
        </section>
      </div>

      {/* Quantitative Analysis */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4 flex items-center gap-2 border-l-4 border-blue-500 pl-2">
          <Ruler className="h-5 w-5 text-blue-500" />
          면적 및 비율 분석
        </h2>
        <div className="grid grid-cols-2 gap-8">
          <div className="space-y-4">
            <MetricCard label="대지면적" value={data.platArea} unit="m²" />
            <MetricCard label="연면적" value={data.totArea} unit="m²" />
          </div>
          <div className="space-y-6">
            <ProgressMetric label="건폐율" value={data.bcRat} target={60} />
            <ProgressMetric label="용적률" value={data.vlrat} target={200} />
          </div>
        </div>
      </section>

      {/* Violation Checklist - Conditional */}
      {data.vlrtBldRgstYn === 'Y' && (
        <section className="mb-8 p-4 border-2 border-red-200 bg-red-50 rounded-xl">
          <h2 className="text-lg font-bold text-red-800 mb-3 flex items-center gap-2">
            <AlertTriangle className="h-5 w-5" />
            위반건축물 행정 위험 체크리스트
          </h2>
          <div className="grid grid-cols-1 gap-2 text-sm text-red-700">
            <div className="flex items-start gap-2">
              <span className="font-bold">□</span>
              <span><strong>이행강제금 부과 여부:</strong> 원상복구 시까지 매년 반복 부과될 수 있습니다.</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="font-bold">□</span>
              <span><strong>영업허가 제한:</strong> 위반 사항 미해결 시 신규 업종의 인허가 및 승계가 제한될 수 있습니다.</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="font-bold">□</span>
              <span><strong>금융권 대출 제한:</strong> 위반건축물 기재 시 담보 대출 한도가 축소되거나 거절될 수 있습니다.</span>
            </div>
            <div className="flex items-start gap-2">
              <span className="font-bold">□</span>
              <span><strong>전세보증보험 가입 불가:</strong> 주택의 경우 HUG 등 보증보험 가입이 거절될 수 있습니다.</span>
            </div>
          </div>
        </section>
      )}

      {/* Additional Details */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-4 flex items-center gap-2 border-l-4 border-blue-500 pl-2">
          <Car className="h-5 w-5 text-blue-500" />
          기타 설비 및 특이사항
        </h2>
        <div className="border rounded-lg overflow-hidden">
          <table className="w-full text-sm">
            <tbody className="divide-y">
              <tr>
                <td className="bg-gray-50 p-3 font-semibold w-1/3 text-center">주차대수</td>
                <td className="p-3 text-center">{data.indrMechUtcnt} 대</td>
              </tr>
              <tr>
                <td className="bg-gray-50 p-3 font-semibold text-center">위반여부</td>
                <td className={`p-3 text-center font-bold ${data.vlrtBldRgstYn === 'Y' ? 'text-red-600' : 'text-green-600'}`}>
                  {data.vlrtBldRgstYn === 'Y' ? '위반건축물' : '정상'}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* Footer / Disclaimer */}
      <div className="mt-auto pt-8 border-t text-[10px] text-gray-400 leading-tight">
        <p>* 본 보고서는 공공데이터포털의 건축물대장 정보를 바탕으로 자동 생성되었습니다.</p>
        <p>* 실제 현황과 대장상 정보가 다를 수 있으므로, 반드시 현장 확인 및 공부 발급을 통해 재확인하시기 바랍니다.</p>
        <p>* 법적 효력이 없는 참고용 자료입니다.</p>
      </div>
    </div>
  );
};

const InfoItem = ({ label, value, icon }: { label: string; value: string | number; icon?: React.ReactNode }) => (
  <div className="flex flex-col">
    <span className="text-xs text-gray-400 flex items-center gap-1">
      {icon} {label}
    </span>
    <span className="font-medium text-gray-800 break-words">{value}</span>
  </div>
);

const MetricCard = ({ label, value, unit }: { label: string; value: number; unit: string }) => (
  <div className="bg-blue-50 p-4 rounded-xl border border-blue-100">
    <div className="text-xs text-blue-500 font-bold mb-1 uppercase tracking-wider">{label}</div>
    <div className="text-2xl font-black text-blue-900">
      {value.toLocaleString()} <span className="text-sm font-normal text-blue-400">{unit}</span>
    </div>
  </div>
);

const ProgressMetric = ({ label, value, target }: { label: string; value: number; target: number }) => {
  const percentage = Math.min((value / target) * 100, 100);
  return (
    <div>
      <div className="flex justify-between text-sm mb-2">
        <span className="font-bold text-gray-700">{label}</span>
        <span className="text-blue-600 font-black">{value}%</span>
      </div>
      <div className="w-full bg-gray-100 rounded-full h-2.5">
        <div 
          className="bg-blue-500 h-2.5 rounded-full transition-all duration-1000" 
          style={{ width: `${percentage}%` }}
        ></div>
      </div>
      <div className="text-[10px] text-gray-400 mt-1 text-right">법정 한도(예시): {target}%</div>
    </div>
  );
};

const formatDate = (dateStr: string) => {
  if (!dateStr || dateStr.length !== 8) return dateStr || '-';
  return `${dateStr.substring(0, 4)}-${dateStr.substring(4, 6)}-${dateStr.substring(6, 8)}`;
};

export default ReportView;
